# Generated by Django 5.0.4 on 2024-04-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=225)),
                ('is_NIS', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MyClass',
        ),
    ]
