# Generated by Django 5.0.4 on 2024-04-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_myschool_delete_myclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('row', models.IntegerField(max_length=40)),
                ('seat', models.IntegerField(max_length=40)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
